const STRING_SUCCESS = "SUCCESS";
const STRING_FAILURE = "FAILURE";

const STRING_DEFAULT_COLOR_ALMACEN = "#d43224";

const STRING_PREGUNTA_SELECCION_SIMPLE = "SELECCION SIMPLE";
const STRING_PREGUNTA_SELECCION_MULTIPLE = "SELECCION MULTIPLE";
const STRING_PREGUNTA_IMAGEN = "IMAGEN";
const STRING_PREGUNTA_COMENTARIO = "COMENTARIO";
const STRING_PREGUNTA_FIRMA = "FIRMA";

module.exports = {
    STRING_SUCCESS,
    STRING_FAILURE,
    STRING_DEFAULT_COLOR_ALMACEN,
    STRING_PREGUNTA_SELECCION_SIMPLE,
    STRING_PREGUNTA_SELECCION_MULTIPLE,
    STRING_PREGUNTA_IMAGEN,
    STRING_PREGUNTA_COMENTARIO,
    STRING_PREGUNTA_FIRMA,
};