const INT_TIPO_QUERY_UPDATE = 1;
const INT_TIPO_QUERY_DELETE = 0;

const INT_PREGUNTA_SELECCION_SIMPLE = 9;
const INT_PREGUNTA_SELECCION_MULTIPLE = 5;
const INT_PREGUNTA_IMAGEN = 6;
const INT_PREGUNTA_COMENTARIO = 7;
const INT_PREGUNTA_FIRMA = 8;

const INT_TIPO_USUARIO_ADMINISTRADOR = 2;
const INT_TIPO_USUARIO_SUB_USUARIO = 3;
const INT_TIPO_USUARIO_AUTOUSUARIO = 29;

const INT_GRUPO_CONCEPTO = {
    FORMULARIO: 3,
};

const INT_BOOLEAN = {
    TRUE: 1,
    FALSE: 0,
};

const INT_CONCEPTO_FORMULARIO = {
    SELECCIONAR_UNIDAD: 11,
    INPUT_ODOMETRO_ACTUAL: 12,
    INPUT_ODOMETRO_PROXIMO: 13,
    FECHA_ACTUAL_CHECKLIST: 14,
    FECHA_PROXIMO_CHECKLIST: 15,
    SELECCIONAR_CONDUCTOR: 16,
    SELECCIONAR_AREA: 17,
    SELECCIONAR_TIPO_CHECKLIST: 18,
    SELECCIONAR_TIPO_VEHICULO: 19,
    SELECCIONAR_MARCA_VEHICULO: 20,
    SELECCIONAR_TIPO_CARROCERIA: 21,
    SELECCIONAR_TIPO_COMBUSTIBLE: 22,
    SELECCIONAR_CIUDAD: 23,
    ULTIMO_ODOMETRO_REGISTRADO: 24,
    ULTIMA_TEMPERATURA_REGISTRADO: 25,
    NIVEL_COMBUSTIBLE: 30,
    MOTIVO: 31,
    NUMERO_DE_CONOCIMIENTO: 32,
    GEOCERCA_ORIGEN: 36,
    GEOCERCA_DESTINO: 37,
    FECHA_PROGRAMADA_VIAJE: 38,
    ODOMETRO_PROXIMO_MANTENIMIENTO: 39,
};

module.exports = {
    INT_TIPO_QUERY_UPDATE,
    INT_TIPO_QUERY_DELETE,
    INT_PREGUNTA_SELECCION_SIMPLE,
    INT_PREGUNTA_SELECCION_MULTIPLE,
    INT_PREGUNTA_IMAGEN,
    INT_PREGUNTA_COMENTARIO,
    INT_PREGUNTA_FIRMA,
    INT_TIPO_USUARIO_ADMINISTRADOR,
    INT_TIPO_USUARIO_SUB_USUARIO,
    INT_TIPO_USUARIO_AUTOUSUARIO,
    INT_GRUPO_CONCEPTO,
    INT_CONCEPTO_FORMULARIO,
    INT_BOOLEAN,
};